version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 5
      - run:
          name: test
          command: docker-compose run java ./gradlew build
      - run:
          name: docker-compose down
          command: docker-compose down
